spring:
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:mem:customerdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    hibernate:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create
    show-sql: 'true'
  application:
    name: appNetCompany
server:
  port: '8088'